### ISSUE TITLE
Long header gets truncated

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/parent-detector#6]
Similarly to https://github.com/raspberrypilearning/gpio-music-box/issues/8 the long header "Program the camera to preview on movement" in worksheet.md gets truncated to "PROGRAM THE CAMERA TO PREVIEW ON" when viewed on http://www.raspberrypi.org/learning/parent-detector/worksheet/

Perhaps the process that converts github-resources into website-resources could be modified to automatically warn you when a header is too long?

**Comment by bennuttall** [comment]
Ok I've just gone and made the headers wider.
