### ISSUE TITLE
sensor variable accessed before initialized

### ISSUE THREAD

**Issue by mrichardson23** [raspberrypilearning/parent-detector#7]
In the code sample on worksheet.md, the `sensor` variable is used before it's initialized with the value 4:

```
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(sensor, GPIO.IN, GPIO.PUD_DOWN)

sensor = 4
```

As reported via Twitter: https://twitter.com/robertabrandao/status/560578371244265475

**Comment by bennuttall** [comment]
Thanks #ellisinnovates girls! And thanks Matt.
